// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbd3TW9f8pTXKS_rIvgSfjnxPqG61Dv8',
    appId: '1:43832340945:web:d086f9aac8cb225ffeb0f0',
    messagingSenderId: '43832340945',
    projectId: 'sheba-ce465',
    authDomain: 'sheba-ce465.firebaseapp.com',
    storageBucket: 'sheba-ce465.appspot.com',
    measurementId: 'G-CNHPJ02EXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKm6O6ldNgRvLMtizlE5VPkv3mq8NBCkw',
    appId: '1:43832340945:android:0742923b034ae15bfeb0f0',
    messagingSenderId: '43832340945',
    projectId: 'sheba-ce465',
    storageBucket: 'sheba-ce465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIkJwEVWFmM8XTGrnBEE-DPP7FmWg3w0',
    appId: '1:43832340945:ios:b98cb6a65184a5f0feb0f0',
    messagingSenderId: '43832340945',
    projectId: 'sheba-ce465',
    storageBucket: 'sheba-ce465.appspot.com',
    iosClientId: '43832340945-g4oh8hjt5g10dic5b0m0n6dnm87njcnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shebaFinancial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIkJwEVWFmM8XTGrnBEE-DPP7FmWg3w0',
    appId: '1:43832340945:ios:b98cb6a65184a5f0feb0f0',
    messagingSenderId: '43832340945',
    projectId: 'sheba-ce465',
    storageBucket: 'sheba-ce465.appspot.com',
    iosClientId: '43832340945-g4oh8hjt5g10dic5b0m0n6dnm87njcnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shebaFinancial',
  );
}
